[project]
name = "nc-story-book-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.31.1",
    "google-genai>=1.73.1",
    "litellm>=1.83.0",
    "openai>=2.33.0",
    "pydantic>=2.13.3",
    "reportlab>=4.5.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
